"use client";

import { Navbar } from "@/components/layout/Navbar";
import { StatusBar } from "@/components/layout/StatusBar";
import { Panel } from "@/components/shared/Panel";
import { useAppStore } from "@/store/useAppStore";
import { useCases } from "@/hooks/useCases";
import { useMemo, useState } from "react";
import { Copy, Download, Check } from "lucide-react";

function buildPython(
  cases: { id: string; tle1: string; tle2: string; schedule: unknown }[]
) {
  const branches = cases
    .map(
      (c) => `    if tle_line1.strip() == ${JSON.stringify(c.tle1.trim())}:
        return ${c.id.toUpperCase()}_SCHEDULE`
    )
    .join("\n");

  const consts = cases
    .map(
      (c) =>
        `${c.id.toUpperCase()}_SCHEDULE = ${JSON.stringify(c.schedule, null, 2)}`
    )
    .join("\n\n");

  return `# Generated by ChunkyWeb — Mission Control
# Auto-generated submission. Embeds pre-planned schedules per case TLE.

${consts}


def plan_imaging(tle_line1: str, tle_line2: str, aoi_polygon, pass_start_utc, pass_end_utc):
    """Return the precomputed schedule matching the given TLE."""
${branches}
    raise ValueError(f"No precomputed schedule for TLE: {tle_line1}")
`;
}

export default function ExportPage() {
  const { data: caseCfgs } = useCases();
  const results = useAppStore((s) => s.results);
  const [copied, setCopied] = useState(false);

  const ready = useMemo(() => {
    if (!caseCfgs) return [];
    return caseCfgs
      .filter((c) => results[c.id]?.plan)
      .map((c) => ({
        id: c.id,
        tle1: c.tle_line1,
        tle2: c.tle_line2,
        schedule: results[c.id].plan!.schedule,
      }));
  }, [caseCfgs, results]);

  const code = useMemo(() => buildPython(ready), [ready]);

  const copy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const download = () => {
    const blob = new Blob([code], { type: "text/x-python" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "my_submission.py";
    a.click();
    URL.revokeObjectURL(url);
  };

  const missing = (caseCfgs ?? []).filter((c) => !results[c.id]?.plan);

  return (
    <div className="flex h-screen flex-col overflow-hidden bg-[var(--paper)] text-[var(--ink)]">
      <Navbar />
      <main className="flex-1 overflow-y-auto">
        <div className="mx-auto flex max-w-[1100px] flex-col gap-8 px-8 py-7">
          <div className="flex items-baseline justify-between border-b border-[var(--ink-rule)] pb-2">
            <span className="figcap">
              Section&nbsp;C
              <span className="mx-2 text-[var(--ink-thread)]">·</span>
              Export
            </span>
            <span className="pagemark">FOLIO 03</span>
          </div>

          <header className="flex flex-col gap-2 border-b-2 border-[var(--ink-rule)] pb-5">
            <span className="figcap">Submission</span>
            <h1
              className="display text-[40px] leading-[1.05] text-[var(--ink)]"
              style={{ letterSpacing: "-0.025em" }}
            >
              Type the schedules to plate.
            </h1>
            <p className="display-italic text-[15px] text-[var(--ink-soft)]">
              Generates a single{" "}
              <span style={{ fontFamily: "var(--font-mono)" }}>
                my_submission.py
              </span>{" "}
              file embedding the schedules for each planned case.
            </p>
          </header>

          {missing.length > 0 && (
            <div
              className="border-y-2 px-5 py-3"
              style={{
                borderColor: "var(--hold)",
                backgroundColor: "var(--hold-soft)",
              }}
            >
              <p className="display-italic text-[13px] text-[var(--ink)]">
                <span
                  className="mr-2 text-[10px] uppercase tracking-[0.18em]"
                  style={{
                    fontFamily: "var(--font-mono)",
                    color: "var(--hold)",
                  }}
                >
                  Hold —
                </span>
                The following cases have not been planned yet and will not be
                embedded:{" "}
                <span style={{ fontFamily: "var(--font-mono)" }}>
                  {missing.map((c) => c.id).join(", ")}
                </span>
              </p>
            </div>
          )}

          <Panel
            figure="FIG 01"
            caption="my_submission.py"
            description={`${ready.length} case(s) embedded`}
            marginalia="plate i"
            bold
            actions={
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={copy}
                  className="flex items-center gap-1.5 border border-[var(--ink)] bg-transparent px-3 py-1.5 text-[10px] uppercase tracking-[0.18em] text-[var(--ink)] transition-colors hover:bg-[var(--ink)] hover:text-[var(--paper)]"
                  style={{ fontFamily: "var(--font-mono)" }}
                >
                  {copied ? <Check size={11} /> : <Copy size={11} />}
                  {copied ? "Copied" : "Copy"}
                </button>
                <button
                  type="button"
                  onClick={download}
                  disabled={ready.length === 0}
                  className="flex items-center gap-1.5 border-2 border-[var(--ink)] bg-[var(--ink)] px-3 py-1.5 text-[10px] uppercase tracking-[0.18em] text-[var(--paper)] transition-colors hover:border-[var(--signal-deep)] hover:bg-[var(--signal)] disabled:cursor-not-allowed disabled:border-[var(--paper-margin)] disabled:bg-[var(--paper-deep)] disabled:text-[var(--ink-faint)]"
                  style={{ fontFamily: "var(--font-mono)" }}
                >
                  <Download size={11} />
                  Download
                </button>
              </div>
            }
          >
            <pre
              className="max-h-[60vh] overflow-auto whitespace-pre-wrap border border-[var(--ink-rule)] bg-[var(--paper-onion)] p-4 text-[11px] leading-relaxed text-[var(--ink)]"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              {code}
            </pre>
          </Panel>
        </div>
      </main>
      <StatusBar />
    </div>
  );
}
