"use client";

import { Navbar } from "@/components/layout/Navbar";
import { StatusBar } from "@/components/layout/StatusBar";
import { Panel } from "@/components/shared/Panel";
import { useAppStore } from "@/store/useAppStore";
import { useCases } from "@/hooks/useCases";
import { useMemo, useState } from "react";
import { Copy, Download, Check } from "lucide-react";

function buildPython(
  cases: { id: string; tle1: string; tle2: string; schedule: unknown }[]
) {
  const tleMap: Record<string, string> = {};
  for (const c of cases) {
    tleMap[c.id] = JSON.stringify(c.schedule, null, 2);
  }

  const branches = cases
    .map(
      (c) => `    if tle_line1.strip() == ${JSON.stringify(c.tle1.trim())}:
        return ${c.id.toUpperCase()}_SCHEDULE`
    )
    .join("\n");

  const consts = cases
    .map(
      (c) =>
        `${c.id.toUpperCase()}_SCHEDULE = ${JSON.stringify(c.schedule, null, 2)}`
    )
    .join("\n\n");

  return `# Generated by ChunkyWeb — Mission Control
# Auto-generated submission. Embeds pre-planned schedules per case TLE.

${consts}


def plan_imaging(tle_line1: str, tle_line2: str, aoi_polygon, pass_start_utc, pass_end_utc):
    """Return the precomputed schedule matching the given TLE."""
${branches}
    raise ValueError(f"No precomputed schedule for TLE: {tle_line1}")
`;
}

export default function ExportPage() {
  const { data: caseCfgs } = useCases();
  const results = useAppStore((s) => s.results);
  const [copied, setCopied] = useState(false);

  const ready = useMemo(() => {
    if (!caseCfgs) return [];
    return caseCfgs
      .filter((c) => results[c.id]?.plan)
      .map((c) => ({
        id: c.id,
        tle1: c.tle_line1,
        tle2: c.tle_line2,
        schedule: results[c.id].plan!.schedule,
      }));
  }, [caseCfgs, results]);

  const code = useMemo(() => buildPython(ready), [ready]);

  const copy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const download = () => {
    const blob = new Blob([code], { type: "text/x-python" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "my_submission.py";
    a.click();
    URL.revokeObjectURL(url);
  };

  const missing = (caseCfgs ?? []).filter((c) => !results[c.id]?.plan);

  return (
    <div className="flex h-screen flex-col overflow-hidden">
      <Navbar />
      <main className="flex-1 overflow-y-auto p-4">
        <div className="mx-auto flex max-w-5xl flex-col gap-4">
          <header className="flex flex-col gap-1">
            <h1
              className="text-lg font-semibold tracking-[0.08em] text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-display)" }}
            >
              EXPORT SUBMISSION
            </h1>
            <p className="text-xs text-[var(--text-muted)]">
              Generates a `my_submission.py` file embedding the schedules for
              each planned case.
            </p>
          </header>

          {missing.length > 0 && (
            <div className="rounded-sm border border-[var(--warning)]/40 bg-[var(--warning-dim)] p-3 text-xs text-[var(--text-primary)]">
              <strong className="text-[var(--warning)]">Heads up:</strong> the
              following cases haven&apos;t been planned yet — they won&apos;t be
              embedded:{" "}
              <span style={{ fontFamily: "var(--font-mono)" }}>
                {missing.map((c) => c.id).join(", ")}
              </span>
            </div>
          )}

          <Panel
            title="my_submission.py"
            subtitle={`${ready.length} case(s) embedded`}
            actions={
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={copy}
                  className="flex items-center gap-1.5 rounded-sm border border-[var(--border-subtle)] bg-[var(--bg-tertiary)] px-3 py-1 text-[10px] uppercase tracking-wider text-[var(--text-primary)] transition-colors hover:bg-[var(--bg-hover)]"
                >
                  {copied ? <Check size={11} /> : <Copy size={11} />}
                  {copied ? "Copied" : "Copy"}
                </button>
                <button
                  type="button"
                  onClick={download}
                  disabled={ready.length === 0}
                  className="flex items-center gap-1.5 rounded-sm border border-[var(--accent-primary)] bg-[var(--accent-primary)] px-3 py-1 text-[10px] uppercase tracking-wider text-white transition-all hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-60"
                >
                  <Download size={11} />
                  Download
                </button>
              </div>
            }
          >
            <pre
              className="max-h-[60vh] overflow-auto whitespace-pre-wrap rounded-sm border border-[var(--border-subtle)] bg-[var(--bg-primary)] p-3 text-[11px] leading-relaxed text-[var(--text-mono)]"
              style={{ fontFamily: "var(--font-mono)" }}
            >
              {code}
            </pre>
          </Panel>
        </div>
      </main>
      <StatusBar />
    </div>
  );
}
